spring:
  application:
    name: event
  redis:
    database: 0
    host: 47.100.249.163
    port: 6379
    password: wework2018
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

server:
  port: 8003

#####rocket-mq######
apache:
  rocketmq:
    consumer:
      PushConsumer: victor_test
      instacneName: victor_test_Consumer
    producer:
      producerGroup: victor_test_Producer
      instacneName: victor_test_Producer
    namesrvAddr: 47.100.249.163:9876
    topic: VictorTest
    tag: VictorTest
#####rocket-mq######

